- hosts: dune1
  tasks: 
    - name: debug
      debug:
        msg: "This is project_1 main deployment playbook; change for tag 1.0"

- hosts: dune1
  tasks:
  - import_role:
      name: service_A
      tasks_from: main.yml
